# Generated by Django 5.2.3 on 2025-06-26 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_summary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
